// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRlzuEr7n49ZF7aQUy96dF3mMmhzpOU_Q',
    appId: '1:378760610898:web:5a5d62b62ae5505e400b8b',
    messagingSenderId: '378760610898',
    projectId: 'inventarioabarrotes-935f9',
    authDomain: 'inventarioabarrotes-935f9.firebaseapp.com',
    storageBucket: 'inventarioabarrotes-935f9.firebasestorage.app',
    measurementId: 'G-PJ9GZG4BG4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlzmnokIyiFZSTPehKSY95jgj7bou7Yps',
    appId: '1:378760610898:android:bbad022394458135400b8b',
    messagingSenderId: '378760610898',
    projectId: 'inventarioabarrotes-935f9',
    storageBucket: 'inventarioabarrotes-935f9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDB-YFklyFL0Vp9DnRAqverAtJlK8KW_H0',
    appId: '1:378760610898:ios:3a904a8f0f4a78d3400b8b',
    messagingSenderId: '378760610898',
    projectId: 'inventarioabarrotes-935f9',
    storageBucket: 'inventarioabarrotes-935f9.firebasestorage.app',
    iosBundleId: 'com.example.inventarioAbarrotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDB-YFklyFL0Vp9DnRAqverAtJlK8KW_H0',
    appId: '1:378760610898:ios:3a904a8f0f4a78d3400b8b',
    messagingSenderId: '378760610898',
    projectId: 'inventarioabarrotes-935f9',
    storageBucket: 'inventarioabarrotes-935f9.firebasestorage.app',
    iosBundleId: 'com.example.inventarioAbarrotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRlzuEr7n49ZF7aQUy96dF3mMmhzpOU_Q',
    appId: '1:378760610898:web:59e037033c16757c400b8b',
    messagingSenderId: '378760610898',
    projectId: 'inventarioabarrotes-935f9',
    authDomain: 'inventarioabarrotes-935f9.firebaseapp.com',
    storageBucket: 'inventarioabarrotes-935f9.firebasestorage.app',
    measurementId: 'G-6X0CXT3LW9',
  );
}
